### ISSUE TITLE
Consider publishing to the WP Plugins directory

### ISSUE THREAD

**Issue by ghost** [brothman01/lity#16]
Hello,

I was looking, for some time now, for an alternative to the now abandoned [“wp-featherlight”](https://github.com/cipherdevgroup/wp-featherlight), and I just stumbled upon your plugin. Based on the description, “lity“ sounds exactly like what I need. Thank you for your hard work! However I am hesitant to install from external sources. Would you please consider publishing to the WP Plugins directory:

https://wordpress.org/plugins/

Published plugins make updates and changelogs so much easier to track for the user. Also, published plugins can get translated into other languages by benevolent contributors through the (relatively new) translation platform:

https://translate.wordpress.org/

**Comment by EvanHerman** [comment]
Hi @defense-commune

We are currently working on getting this thing prepped and ready for submission into the WordPress.org plugin directory. We're hoping to get it submitted for approval today. It may take a few days for them to review and approve, but once it's been approved I'll comment back here with a direct link to it there.

Thanks for the comment here and giving the plugin a look at before it was ever publicly available!

Evan

**Comment by EvanHerman** [comment]
@defense-commune 

Sorry for the delay. I had to get a few loose ends tied up in the plugin and get it fully ready for release.

I went ahead and got things submitted, reviewed and approved on WordPress.org. You can find the new plugin listed at https://wordpress.org/plugins/lity-responsive-lightboxes/

If you do go ahead and use the plugin, and you run into any issues or have any questions, feel free to open up a new issue here on GitHub and I'll help out the best I can.

Evan
